export const columns = [
    {
        id: "name",
        numeric: false,
        disablePadding: false,
        label: "Naam",
    },
    {
        id: "client",
        numeric: false,
        disablePadding: false,
        label: "Klant",
    },
    {
        id: "project",
        numeric: false,
        disablePadding: false,
        label: "Project",
    },
    {
        id: "worked",
        numeric: true,
        disablePadding: true,
        label: "Gewerkt",
    },
    {
        id: "overtime",
        numeric: true,
        disablePadding: true,
        label: "Overwerk",
    },
    {
        id: "sick",
        numeric: true,
        disablePadding: true,
        label: "Ziek",
    },
    {
        id: "holiday",
        numeric: true,
        disablePadding: true,
        label: "Verlof",
    },
    {
        id: "publicHoliday",
        numeric: true,
        disablePadding: true,
        label: "Feestdag",
    },
    {
        id: "available",
        numeric: true,
        disablePadding: true,
        label: "Beschikb.",
    },
    {
        id: "education",
        numeric: true,
        disablePadding: true,
        label: "Opl.",
    },
    {
        id: "other",
        numeric: true,
        disablePadding: true,
        label: "Overig",
    },
    {
        id: "standBy",
        numeric: true,
        disablePadding: true,
        label: "stand-by",
    },
    {
        id: "kilometers",
        numeric: true,
        disablePadding: false,
        label: "Km",
    },
    {
        id: "approved",
        numeric: false,
        disablePadding: false,
        label: "Akkoord",
    },
];
