export const mockDays = [
    {
        day: 1,
        date: new Date(2020, 3, 1),
        worked: "",
        overtime: "",
        sick: "",
        holiday: "",
        publicHoliday: "",
        available: "",
        education: "",
        other: "",
        standBy: "",
        kilometers: "",
        explanation: "",
    },
    {
        day: 2,
        date: new Date(2020, 3, 2),
        worked: "",
        overtime: "",
        sick: "",
        holiday: "",
        publicHoliday: "",
        available: "",
        education: "",
        other: "",
        standBy: "",
        kilometers: "",
        explanation: "",
    },
    {
        day: 3,
        date: new Date(2020, 3, 3),
        worked: "",
        overtime: "",
        sick: "",
        holiday: "",
        publicHoliday: "",
        available: "",
        education: "",
        other: "",
        standBy: "",
        kilometers: "",
        explanation: "",
    },
    {
        day: 4,
        date: new Date(2020, 3, 4),
        worked: "",
        overtime: "",
        sick: "",
        holiday: "",
        publicHoliday: "",
        available: "",
        education: "",
        other: "",
        standBy: "",
        kilometers: "",
        explanation: "",
    },
    {
        day: 5,
        date: new Date(2020, 3, 5),
        worked: "",
        overtime: "",
        sick: "",
        holiday: "",
        publicHoliday: "",
        available: "",
        education: "",
        other: "",
        standBy: "",
        kilometers: "",
        explanation: "",
    },
];

export const mockDaysChanged = [
    {
        day: 1,
        date: new Date(2020, 3, 1),
        worked: 8,
        overtime: "",
        sick: "",
        holiday: "",
        publicHoliday: "",
        available: "",
        education: "",
        other: "",
        standBy: "",
        kilometers: "",
        explanation: "",
    },
    {
        day: 2,
        date: new Date(2020, 3, 2),
        worked: "",
        overtime: "",
        sick: "",
        holiday: "",
        publicHoliday: "",
        available: "",
        education: "",
        other: "",
        standBy: "",
        kilometers: "",
        explanation: "",
    },
    {
        day: 3,
        date: new Date(2020, 3, 3),
        worked: "",
        overtime: "",
        sick: "",
        holiday: "",
        publicHoliday: "",
        available: "",
        education: "",
        other: "",
        standBy: "",
        kilometers: "",
        explanation: "",
    },
    {
        day: 4,
        date: new Date(2020, 3, 4),
        worked: "",
        overtime: "",
        sick: "",
        holiday: "",
        publicHoliday: "",
        available: "",
        education: "",
        other: "",
        standBy: "",
        kilometers: "",
        explanation: "",
    },
    {
        day: 5,
        date: new Date(2020, 3, 5),
        worked: "",
        overtime: "",
        sick: "",
        holiday: "",
        publicHoliday: "",
        available: "",
        education: "",
        other: "",
        standBy: "",
        kilometers: "",
        explanation: "",
    },
];

export const mockWeekend = [
    {
        day: 4,
        date: new Date(2020, 3, 4),
        worked: "",
        overtime: "",
        sick: "",
        holiday: "",
        publicHoliday: "",
        available: "",
        education: "",
        other: "",
        standBy: "",
        kilometers: "",
        explanation: "",
    },
    {
        day: 5,
        date: new Date(2020, 3, 5),
        worked: "",
        overtime: "",
        sick: "",
        holiday: "",
        publicHoliday: "",
        available: "",
        education: "",
        other: "",
        standBy: "",
        kilometers: "",
        explanation: "",
    },
];

export const mockColumns = [
    {
        id: "worked",
        description: "Gewerkt",
        enabled: true,
    },
    {
        id: "overtime",
        description: "Overwerk",
        enabled: true,
    },
    {
        id: "sick",
        description: "Ziek",
        enabled: true,
    },
    {
        id: "holiday",
        description: "Verlof",
        enabled: true,
    },
    {
        id: "publicHoliday",
        description: "Feestdag",
        enabled: true,
    },
    {
        id: "available",
        description: "Beschikbaar",
        enabled: false,
    },
    {
        id: "education",
        description: "Opleiding",
        enabled: false,
    },
    {
        id: "other",
        description: "Overig",
        enabled: false,
    },
    {
        id: "standBy",
        description: "StandBy",
        enabled: false,
    },
    {
        id: "kilometers",
        description: "Kilometers",
        enabled: false,
    },
];

export const mockProfile = {
    displayName: "Test Codezilla",
    email: "test@codezilla.nl",
    microsoftId: "testMicrosoftId",
    id: "testId",
};
