export const mockDays = [
    {
        day: 1,
        date: new Date(2020, 3, 1),
        worked: "",
        overtime: "",
        sick: "",
        holiday: "",
        publicHoliday: "",
        available: "",
        education: "",
        other: "",
        standBy: "",
        kilometers: "",
        explanation: "",
    },
    {
        day: 2,
        date: new Date(2020, 3, 2),
        worked: "",
        overtime: "",
        sick: "",
        holiday: "",
        publicHoliday: "",
        available: "",
        education: "",
        other: "",
        standBy: "",
        kilometers: "",
        explanation: "",
    },
    {
        day: 3,
        date: new Date(2020, 3, 3),
        worked: "",
        overtime: "",
        sick: "",
        holiday: "",
        publicHoliday: "",
        available: "",
        education: "",
        other: "",
        standBy: "",
        kilometers: "",
        explanation: "",
    },
    {
        day: 4,
        date: new Date(2020, 3, 4),
        worked: "",
        overtime: "",
        sick: "",
        holiday: "",
        publicHoliday: "",
        available: "",
        education: "",
        other: "",
        standBy: "",
        kilometers: "",
        explanation: "",
    },
    {
        day: 5,
        date: new Date(2020, 3, 5),
        worked: "",
        overtime: "",
        sick: "",
        holiday: "",
        publicHoliday: "",
        available: "",
        education: "",
        other: "",
        standBy: "",
        kilometers: "",
        explanation: "",
    },
];

export const mockWeekend = [
    {
        day: 4,
        date: new Date(2020, 3, 4),
        worked: "",
        overtime: "",
        sick: "",
        holiday: "",
        publicHoliday: "",
        available: "",
        education: "",
        other: "",
        standBy: "",
        kilometers: "",
        explanation: "",
    },
    {
        day: 5,
        date: new Date(2020, 3, 5),
        worked: "",
        overtime: "",
        sick: "",
        holiday: "",
        publicHoliday: "",
        available: "",
        education: "",
        other: "",
        standBy: "",
        kilometers: "",
        explanation: "",
    },
];
